### ISSUE TITLE
CHANNEL ID failed to Read Properly

### ISSUE THREAD

**Issue by azmiord** [hotsno/linkedin-jobs-notifier#1]
Hi, thank you for this amazing project!

I encounter some error, tho i have edited the env file as instructed.
![image](https://github.com/hotsno/linkedin-jobs-notifier/assets/163746269/db00612d-8e13-435f-8635-6feb5bee727f)

![image](https://github.com/hotsno/linkedin-jobs-notifier/assets/163746269/a525e141-7355-4791-9e6e-c52969006b14)

I hope you reply this and help me to implement your bot.

thank you

**Comment by hereisprabhat** [comment]
you need to change the name of `.env.example` to `.env`
